version: 0.2
phases:
 install:
   commands:
     - echo Installing...
 build:
   commands:
     - echo Build started
 post_build:
   commands:
     - echo Deploying to EC2
     - ssh -o StrictHostKeyChecking=no ec2-user@$EC2_HOST "cd cicd-app && git pull && npm install && pm2 restart all"version: 0.2
phases:
 install:
   commands:
     - npm install || true
 build:
   commands:
     - echo Build step
 post_build:
   commands:
     - echo Deployment step
